Repository awslabs/mcp, pull requests merged in 2025-10, with the labels that each got.

#1412 fix(doc): fix IAM policy definition in README
  src/aws-dataprocessing-mcp-server/README.md
Labels: ready-for-merge

#1305 docs: Add Getting Started with Claude Code section to README
  README.md
Labels: ready-for-merge

#1418 fix: backout docusaurus update
  docusaurus/package-lock.json
  docusaurus/package.json
Labels: 👮admin👮

#1420 chore: release/2025.10.20251002031219
  src/amazon-bedrock-agentcore-mcp-server/awslabs/amazon_bedrock_agentcore_mcp_server/__init__.py
  src/amazon-bedrock-agentcore-mcp-server/pyproject.toml
  src/amazon-bedrock-agentcore-mcp-server/uv.lock
  src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/__init__.py
  src/aws-dataprocessing-mcp-server/pyproject.toml
  src/aws-dataprocessing-mcp-server/uv.lock
  src/redshift-mcp-server/awslabs/redshift_mcp_server/__init__.py
  src/redshift-mcp-server/pyproject.toml
  src/redshift-mcp-server/uv.lock
Labels: ready-for-merge

#1423 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: ready-for-merge, 👮admin👮

#1425 fix: update iot sitewise container image
  src/aws-iot-sitewise-mcp-server/Dockerfile
  src/aws-iot-sitewise-mcp-server/awslabs/aws_iot_sitewise_mcp_server/prompts/data_exploration.py
  src/aws-iot-sitewise-mcp-server/awslabs/aws_iot_sitewise_mcp_server/prompts/data_ingestion.py
Labels: ready-for-merge, 👮admin👮

#1432 fix: add maintainers to all src
  .github/CODEOWNERS
Labels: ready-for-merge, 👮admin👮

#1322 docs(aws-api-mcp): improve contributing guide
  src/aws-api-mcp-server/CONTRIBUTING.md
Labels: aws-api-mcp

#1243 fix: update alpine base images
  src/amazon-kendra-index-mcp-server/Dockerfile
  src/amazon-mq-mcp-server/Dockerfile
  src/amazon-neptune-mcp-server/Dockerfile
  src/amazon-qbusiness-anonymous-mcp-server/Dockerfile
  src/amazon-rekognition-mcp-server/Dockerfile
  src/amazon-sns-sqs-mcp-server/Dockerfile
  src/aurora-dsql-mcp-server/Dockerfile
  src/aws-appsync-mcp-server/Dockerfile
  src/aws-bedrock-custom-model-import-mcp-server/Dockerfile
  src/aws-bedrock-data-automation-mcp-server/Dockerfile
  src/aws-dataprocessing-mcp-server/Dockerfile
  src/aws-diagram-mcp-server/Dockerfile
  src/aws-documentation-mcp-server/Dockerfile
  src/aws-healthomics-mcp-server/Dockerfile
  src/aws-location-mcp-server/Dockerfile
  src/aws-msk-mcp-server/Dockerfile
  src/aws-pricing-mcp-server/Dockerfile
  src/bedrock-kb-retrieval-mcp-server/Dockerfile
  src/billing-cost-management-mcp-server/Dockerfile
  src/cdk-mcp-server/Dockerfile
  src/cfn-mcp-server/Dockerfile
  src/cloudwatch-appsignals-mcp-server/Dockerfile
  src/cloudwatch-logs-mcp-server/Dockerfile
  src/cloudwatch-mcp-server/Dockerfile
  src/cost-explorer-mcp-server/Dockerfile
  src/dynamodb-mcp-server/Dockerfile
  src/eks-mcp-server/Dockerfile
  src/elasticache-mcp-server/Dockerfile
  src/iam-mcp-server/Dockerfile
  src/lambda-tool-mcp-server/Dockerfile
  src/memcached-mcp-server/Dockerfile
  src/mysql-mcp-server/Dockerfile
  src/nova-canvas-mcp-server/Dockerfile
  src/openapi-mcp-server/Dockerfile
  src/postgres-mcp-server/Dockerfile
  src/prometheus-mcp-server/Dockerfile
  src/redshift-mcp-server/Dockerfile
  src/stepfunctions-tool-mcp-server/Dockerfile
  src/timestream-for-influxdb-mcp-server/Dockerfile
  src/valkey-mcp-server/Dockerfile
Labels: stale
