Repository awslabs/mcp, pull requests merged in 2025-09, with the labels that each got.

#1236 fix: pinned dependency for uv in healthlake
  src/healthlake-mcp-server/Dockerfile
  src/healthlake-mcp-server/uv-requirements.txt
Labels: ready-for-merge

#1258 chore: release/2025.09.20250909205525
  src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
  src/aws-api-mcp-server/pyproject.toml
  src/aws-api-mcp-server/uv.lock
  src/aws-diagram-mcp-server/awslabs/aws_diagram_mcp_server/__init__.py
  src/aws-diagram-mcp-server/pyproject.toml
  src/aws-diagram-mcp-server/uv.lock
  src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/__init__.py
  src/aws-documentation-mcp-server/pyproject.toml
  src/aws-documentation-mcp-server/uv.lock
  src/ccapi-mcp-server/awslabs/ccapi_mcp_server/__init__.py
  src/ccapi-mcp-server/pyproject.toml
  src/ccapi-mcp-server/uv.lock
  src/cloudtrail-mcp-server/awslabs/cloudtrail_mcp_server/__init__.py
  src/cloudtrail-mcp-server/pyproject.toml
  src/cloudtrail-mcp-server/uv.lock
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/__init__.py
  src/dynamodb-mcp-server/pyproject.toml
  src/dynamodb-mcp-server/uv.lock
  src/ecs-mcp-server/awslabs/ecs_mcp_server/__init__.py
  src/ecs-mcp-server/pyproject.toml
  src/ecs-mcp-server/uv.lock
  src/healthlake-mcp-server/awslabs/healthlake_mcp_server/__init__.py
  src/healthlake-mcp-server/pyproject.toml
  src/healthlake-mcp-server/uv.lock
  src/well-architected-security-mcp-server/awslabs/well_architected_security_mcp_server/__init__.py
  src/well-architected-security-mcp-server/pyproject.toml
  src/well-architected-security-mcp-server/uv.lock
Labels: code-review, 👮admin👮

#1281 fix(msk): annotate tool with description for msk-mcp-server
  src/aws-msk-mcp-server/README.md
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/logs_and_telemetry/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/mutate_cluster/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/mutate_config/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/mutate_vpc/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/read_cluster/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/read_config/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/read_global/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/read_vpc/__init__.py
  src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/tools/static_tools/__init__.py
  src/aws-msk-mcp-server/makefile
  src/aws-msk-mcp-server/tests/test_mutate_config_init.py
  src/aws-msk-mcp-server/tests/test_mutate_vpc_init.py
  src/aws-msk-mcp-server/tests/test_read_cluster_init_updated.py
  src/aws-msk-mcp-server/tests/test_read_config_init.py
  src/aws-msk-mcp-server/tests/test_read_config_init_updated.py
  src/aws-msk-mcp-server/tests/test_read_global_init.py
  src/aws-msk-mcp-server/tests/test_static_tools_init.py
  src/aws-msk-mcp-server/tests/test_tool_descriptions.py
  src/aws-msk-mcp-server/uv.lock
Labels: waiting-for-codeowners

#1374 fix: Updating User-Agent in tests
  src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/server_utils.py
  src/aws-documentation-mcp-server/tests/constants.py
  src/aws-documentation-mcp-server/tests/test_aws_cn_get_available_services_live.py
  src/aws-documentation-mcp-server/tests/test_aws_cn_read_documentation_live.py
  src/aws-documentation-mcp-server/tests/test_aws_read_documentation_live.py
  src/aws-documentation-mcp-server/tests/test_aws_recommend_live.py
  src/aws-documentation-mcp-server/tests/test_aws_search_live.py
Labels: waiting-for-codeowners
