Repository awslabs/mcp, pull requests merged in 2025-08, with the labels that each got.

#1021 docs: fixing readme
  src/postgres-mcp-server/README.md
Labels: ready-for-merge

#1033 chore: release/2025.08.20250806001353
  src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
  src/aws-api-mcp-server/pyproject.toml
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/__init__.py
  src/dynamodb-mcp-server/pyproject.toml
Labels: ready-for-merge

#995 fix(eks-mcp-server): support HTTP(S)_PROXY env var when building k8s client
  src/eks-mcp-server/README.md
  src/eks-mcp-server/awslabs/eks_mcp_server/k8s_apis.py
  src/eks-mcp-server/tests/test_k8s_apis.py
  src/eks-mcp-server/uv.lock
Labels: ready-for-merge

#1107 chore: upgrade uv to 0.8.10
  .github/workflows/dependency-review-action.yml
  src/amazon-kendra-index-mcp-server/uv-requirements.txt
  src/amazon-mq-mcp-server/uv-requirements.txt
  src/amazon-neptune-mcp-server/uv-requirements.txt
  src/amazon-qbusiness-anonymous-mcp-server/uv-requirements.txt
  src/amazon-rekognition-mcp-server/uv-requirements.txt
  src/amazon-sns-sqs-mcp-server/uv-requirements.txt
  src/aurora-dsql-mcp-server/uv-requirements.txt
  src/aws-api-mcp-server/uv-requirements.txt
  src/aws-bedrock-data-automation-mcp-server/uv-requirements.txt
  src/aws-dataprocessing-mcp-server/uv-requirements.txt
  src/aws-diagram-mcp-server/uv-requirements.txt
  src/aws-documentation-mcp-server/uv-requirements.txt
  src/aws-healthomics-mcp-server/uv-requirements.txt
  src/aws-location-mcp-server/uv-requirements.txt
  src/aws-msk-mcp-server/uv-requirements.txt
  src/aws-pricing-mcp-server/uv-requirements.txt
  src/bedrock-kb-retrieval-mcp-server/uv-requirements.txt
  src/ccapi-mcp-server/uv-requirements.txt
  src/cdk-mcp-server/uv-requirements.txt
  src/cfn-mcp-server/uv-requirements.txt
  src/cloudwatch-appsignals-mcp-server/uv-requirements.txt
  src/cloudwatch-logs-mcp-server/uv-requirements.txt
  src/cloudwatch-mcp-server/uv-requirements.txt
  src/core-mcp-server/uv-requirements.txt
  src/cost-explorer-mcp-server/uv-requirements.txt
  src/dynamodb-mcp-server/uv-requirements.txt
  src/eks-mcp-server/uv-requirements.txt
  src/elasticache-mcp-server/uv-requirements.txt
  src/iam-mcp-server/uv-requirements.txt
  src/lambda-tool-mcp-server/uv-requirements.txt
  src/memcached-mcp-server/uv-requirements.txt
  src/mysql-mcp-server/uv-requirements.txt
  src/nova-canvas-mcp-server/uv-requirements.txt
  src/openapi-mcp-server/uv-requirements.txt
  src/postgres-mcp-server/uv-requirements.txt
  src/prometheus-mcp-server/uv-requirements.txt
  src/redshift-mcp-server/uv-requirements.txt
  src/s3-tables-mcp-server/uv-requirements.txt
  src/stepfunctions-tool-mcp-server/uv-requirements.txt
  src/terraform-mcp-server/uv-requirements.txt
  src/timestream-for-influxdb-mcp-server/uv-requirements.txt
  src/valkey-mcp-server/uv-requirements.txt
Labels: dependencies

#1174 fix: (redshift-mcp-server) Implement proper AWS region precedence following AWS CLI standards
  src/redshift-mcp-server/README.md
  src/redshift-mcp-server/awslabs/redshift_mcp_server/consts.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/redshift.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/server.py
  src/redshift-mcp-server/tests/test_redshift.py
  src/redshift-mcp-server/uv.lock
Labels: ready-for-merge, 👮admin👮

#1122 feat: New HealthLake MCP Server
  .github/CODEOWNERS
  README.md
  docusaurus/docs/servers/healthlake-mcp-server.md
  docusaurus/sidebars.ts
  docusaurus/static/assets/server-cards.json
  src/healthlake-mcp-server/.dockerignore
  src/healthlake-mcp-server/.gitignore
  src/healthlake-mcp-server/.python-version
  src/healthlake-mcp-server/CHANGELOG.md
  src/healthlake-mcp-server/CONTRIBUTING.md
  src/healthlake-mcp-server/Dockerfile
  src/healthlake-mcp-server/LICENSE
  src/healthlake-mcp-server/NOTICE
  src/healthlake-mcp-server/README.md
  src/healthlake-mcp-server/awslabs/__init__.py
  src/healthlake-mcp-server/awslabs/healthlake_mcp_server/__init__.py
  src/healthlake-mcp-server/awslabs/healthlake_mcp_server/fhir_operations.py
  src/healthlake-mcp-server/awslabs/healthlake_mcp_server/main.py
  src/healthlake-mcp-server/awslabs/healthlake_mcp_server/models.py
  src/healthlake-mcp-server/awslabs/healthlake_mcp_server/server.py
  src/healthlake-mcp-server/docker-healthcheck.sh
  src/healthlake-mcp-server/examples/README.md
  src/healthlake-mcp-server/examples/mcp_config.json
  src/healthlake-mcp-server/pyproject.toml
  src/healthlake-mcp-server/tests/conftest.py
  src/healthlake-mcp-server/tests/test_fhir_client_comprehensive.py
  src/healthlake-mcp-server/tests/test_fhir_error_scenarios.py
  src/healthlake-mcp-server/tests/test_fhir_operations.py
  src/healthlake-mcp-server/tests/test_integration_mock_based.py
  src/healthlake-mcp-server/tests/test_main.py
  src/healthlake-mcp-server/tests/test_main_edge_cases.py
  src/healthlake-mcp-server/tests/test_mcp_integration_coverage.py
  src/healthlake-mcp-server/tests/test_models.py
  src/healthlake-mcp-server/tests/test_models_edge_cases.py
  src/healthlake-mcp-server/tests/test_readonly_mode.py
  src/healthlake-mcp-server/tests/test_server_core.py
  src/healthlake-mcp-server/tests/test_server_error_handling.py
  src/healthlake-mcp-server/tests/test_server_mcp_handlers.py
  src/healthlake-mcp-server/tests/test_server_toolhandler.py
  src/healthlake-mcp-server/tests/test_server_validation.py
  src/healthlake-mcp-server/uv-requirements.txt
  src/healthlake-mcp-server/uv.lock
Labels: new mcp server
