Repository awslabs/mcp, pull requests merged in 2025-06, with the labels that each got.

#401 feat(Keyspaces): Add MCP support for Amazon Keyspaces
  .github/CODEOWNERS
  .gitignore
  README.md
  docs/index.md
  docs/servers/amazon-keyspaces-mcp-server.md
  src/amazon-keyspaces-mcp-server/.gitignore
  src/amazon-keyspaces-mcp-server/.python-version
  src/amazon-keyspaces-mcp-server/CHANGELOG.md
  src/amazon-keyspaces-mcp-server/LICENSE
  src/amazon-keyspaces-mcp-server/NOTICE
  src/amazon-keyspaces-mcp-server/README.md
  src/amazon-keyspaces-mcp-server/awslabs/__init__.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/__init__.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/client.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/config.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/consts.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/llm_context.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/models.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/server.py
  src/amazon-keyspaces-mcp-server/awslabs/amazon_keyspaces_mcp_server/services.py
  src/amazon-keyspaces-mcp-server/pyproject.toml
  src/amazon-keyspaces-mcp-server/run_tests.sh
  src/amazon-keyspaces-mcp-server/tests/__init__.py
  src/amazon-keyspaces-mcp-server/tests/test_client.py
  src/amazon-keyspaces-mcp-server/tests/test_init.py
  src/amazon-keyspaces-mcp-server/tests/test_main.py
  src/amazon-keyspaces-mcp-server/tests/test_query_analysis_service.py
  src/amazon-keyspaces-mcp-server/tests/test_server.py
  src/amazon-keyspaces-mcp-server/tests/test_services.py
  src/amazon-keyspaces-mcp-server/uv.lock
Labels: new mcp server

#472 feat: add Bedrock Data Automation mcp server
  README.md
  docs/index.md
  docs/servers/aws-bedrock-data-automation-mcp-server.md
  src/aws-bedrock-data-automation-mcp-server/.gitignore
  src/aws-bedrock-data-automation-mcp-server/.pre-commit-config.yaml
  src/aws-bedrock-data-automation-mcp-server/.python-version
  src/aws-bedrock-data-automation-mcp-server/CHANGELOG.md
  src/aws-bedrock-data-automation-mcp-server/Dockerfile
  src/aws-bedrock-data-automation-mcp-server/LICENSE
  src/aws-bedrock-data-automation-mcp-server/NOTICE
  src/aws-bedrock-data-automation-mcp-server/README.md
  src/aws-bedrock-data-automation-mcp-server/awslabs/__init__.py
  src/aws-bedrock-data-automation-mcp-server/awslabs/aws_bedrock_data_automation_mcp_server/__init__.py
  src/aws-bedrock-data-automation-mcp-server/awslabs/aws_bedrock_data_automation_mcp_server/helpers.py
  src/aws-bedrock-data-automation-mcp-server/awslabs/aws_bedrock_data_automation_mcp_server/server.py
  src/aws-bedrock-data-automation-mcp-server/docker-healthcheck.sh
  src/aws-bedrock-data-automation-mcp-server/pyproject.toml
  src/aws-bedrock-data-automation-mcp-server/tests/__init__.py
  src/aws-bedrock-data-automation-mcp-server/tests/test_helpers.py
  src/aws-bedrock-data-automation-mcp-server/tests/test_init.py
  src/aws-bedrock-data-automation-mcp-server/tests/test_main.py
  src/aws-bedrock-data-automation-mcp-server/tests/test_server.py
  src/aws-bedrock-data-automation-mcp-server/uv.lock
Labels: new mcp server

#533 fix: cookiecutter license and updates
  .gitignore
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/Dockerfile
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/awslabs/__init__.py
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/awslabs/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-') | replace('-', '_')}}_mcp_server/__init__.py
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/awslabs/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-') | replace('-', '_')}}_mcp_server/server.py
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/docker-healthcheck.sh
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/pyproject.toml
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/test_init.py
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/test_main.py
  python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/test_server.py
Labels: ready-for-merge

#535 docs: suggest using IAM role instead of user on AMQ and SNS-SQS MCP
  src/amazon-mq-mcp-server/README.md
  src/amazon-sns-sqs-mcp-server/README.md
Labels: ready-for-merge, waiting-for-codeowners

#540 chore: openssf scorecard pinned dependencies
  .github/workflows/cfn_nag.yml
  .github/workflows/checkov.yml
  .github/workflows/claude.yml
  .github/workflows/codeql.yml
  .github/workflows/powershell.yml
  .github/workflows/semgrep.yml
  .github/workflows/trivy.yml
  src/amazon-kendra-index-mcp-server/Dockerfile
  src/amazon-mq-mcp-server/Dockerfile
  src/amazon-neptune-mcp-server/Dockerfile
  src/amazon-sns-sqs-mcp-server/Dockerfile
  src/aurora-dsql-mcp-server/Dockerfile
  src/aws-bedrock-data-automation-mcp-server/Dockerfile
  src/aws-diagram-mcp-server/Dockerfile
  src/aws-documentation-mcp-server/Dockerfile
  src/aws-location-mcp-server/Dockerfile
  src/bedrock-kb-retrieval-mcp-server/Dockerfile
  src/cdk-mcp-server/Dockerfile
  src/cfn-mcp-server/Dockerfile
  src/cloudwatch-logs-mcp-server/Dockerfile
  src/core-mcp-server/Dockerfile
  src/cost-analysis-mcp-server/Dockerfile
  src/dynamodb-mcp-server/Dockerfile
  src/eks-mcp-server/Dockerfile
  src/lambda-tool-mcp-server/Dockerfile
  src/memcached-mcp-server/Dockerfile
  src/mysql-mcp-server/Dockerfile
  src/nova-canvas-mcp-server/Dockerfile
  src/postgres-mcp-server/Dockerfile
  src/stepfunctions-tool-mcp-server/Dockerfile
  src/terraform-mcp-server/Dockerfile
  src/valkey-mcp-server/Dockerfile
Labels: github_actions, ready-for-merge

#542 docs: fix typos
  src/eks-mcp-server/awslabs/eks_mcp_server/eks_kb_handler.py
  src/lambda-tool-mcp-server/examples/README.md
Labels: ready-for-merge

#553 fix: invalid JSON for cloudwatch-logs-mcp-server example
  src/cloudwatch-logs-mcp-server/README.md
Labels: ready-for-merge

#547 fix: update to commit hash
  .github/workflows/cfn_nag.yml
Labels: github_actions, ready-for-merge

#566 refactor: remove redundant pre-commit configs
  .pre-commit-config.yaml
  src/amazon-kendra-index-mcp-server/.pre-commit-config.yaml
  src/amazon-mq-mcp-server/.pre-commit-config.yaml
  src/amazon-neptune-mcp-server/.pre-commit-config.yaml
  src/amazon-sns-sqs-mcp-server/.pre-commit-config.yaml
  src/aurora-dsql-mcp-server/.pre-commit-config.yaml
  src/aws-bedrock-data-automation-mcp-server/.pre-commit-config.yaml
  src/aws-diagram-mcp-server/.pre-commit-config.yaml
  src/aws-documentation-mcp-server/.pre-commit-config.yaml
  src/aws-location-mcp-server/.pre-commit-config.yaml
  src/bedrock-kb-retrieval-mcp-server/.pre-commit-config.yaml
  src/cdk-mcp-server/.pre-commit-config.yaml
  src/cfn-mcp-server/.pre-commit-config.yaml
  src/cloudwatch-logs-mcp-server/.pre-commit-config.yaml
  src/code-doc-gen-mcp-server/.pre-commit-config.yaml
  src/core-mcp-server/.pre-commit-config.yaml
  src/cost-analysis-mcp-server/.pre-commit-config.yaml
  src/cost-explorer-mcp-server/.pre-commit-config.yaml
  src/documentdb-mcp-server/.pre-commit-config.yaml
  src/dynamodb-mcp-server/.pre-commit-config.yaml
  src/eks-mcp-server/.pre-commit-config.yaml
  src/finch-mcp-server/.pre-commit-config.yaml
  src/frontend-mcp-server/.pre-commit-config.yaml
  src/git-repo-research-mcp-server/.pre-commit-config.yaml
  src/lambda-tool-mcp-server/.pre-commit-config.yaml
  src/memcached-mcp-server/.pre-commit-config.yaml
  src/nova-canvas-mcp-server/.pre-commit-config.yaml
  src/postgres-mcp-server/.pre-commit-config.yaml
  src/stepfunctions-tool-mcp-server/.pre-commit-config.yaml
  src/syntheticdata-mcp-server/.pre-commit-config.yaml
  src/terraform-mcp-server/.pre-commit-config.yaml
  src/valkey-mcp-server/.pre-commit-config.yaml
Labels: ready-for-merge

#565 fix(dynamodb-mcp-server): improve documentation for DynamoDB attribute value format
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/server.py
Labels: waiting-for-codeowners

#461 feat: Amazon Timestream for InfluxDB Local MCP Server
  .github/CODEOWNERS
  README.md
  docs/index.md
  docs/servers/timestream-for-influxdb-mcp-server.md
  mkdocs.yml
  src/timestream-for-influxdb-mcp-server/.gitignore
  src/timestream-for-influxdb-mcp-server/.pre-commit-config.yaml
  src/timestream-for-influxdb-mcp-server/.python-version
  src/timestream-for-influxdb-mcp-server/CHANGELOG.md
  src/timestream-for-influxdb-mcp-server/Dockerfile
  src/timestream-for-influxdb-mcp-server/LICENSE
  src/timestream-for-influxdb-mcp-server/NOTICE
  src/timestream-for-influxdb-mcp-server/README.md
  src/timestream-for-influxdb-mcp-server/awslabs/__init__.py
  src/timestream-for-influxdb-mcp-server/awslabs/timestream_for_influxdb_mcp_server/__init__.py
  src/timestream-for-influxdb-mcp-server/awslabs/timestream_for_influxdb_mcp_server/server.py
  src/timestream-for-influxdb-mcp-server/docker-healthcheck.sh
  src/timestream-for-influxdb-mcp-server/pyproject.toml
  src/timestream-for-influxdb-mcp-server/tests/test_init.py
  src/timestream-for-influxdb-mcp-server/tests/test_main.py
  src/timestream-for-influxdb-mcp-server/tests/test_server.py
  src/timestream-for-influxdb-mcp-server/uv.lock
Labels: new mcp server

#395 feat: Add Prometheus MCP for AWS Managed Prometheus
  .github/CODEOWNERS
  .github/workflows/check-license-header.json
  README.md
  docs/index.md
  docs/servers/prometheus-mcp-server.md
  mkdocs.yml
  src/prometheus-mcp-server/.python-version
  src/prometheus-mcp-server/CHANGELOG.md
  src/prometheus-mcp-server/Dockerfile
  src/prometheus-mcp-server/LICENSE
  src/prometheus-mcp-server/NOTICE
  src/prometheus-mcp-server/README.md
  src/prometheus-mcp-server/awslabs/__init__.py
  src/prometheus-mcp-server/awslabs/prometheus_mcp_server/__init__.py
  src/prometheus-mcp-server/awslabs/prometheus_mcp_server/consts.py
  src/prometheus-mcp-server/awslabs/prometheus_mcp_server/models.py
  src/prometheus-mcp-server/awslabs/prometheus_mcp_server/server.py
  src/prometheus-mcp-server/docker-healthcheck.sh
  src/prometheus-mcp-server/pyproject.toml
  src/prometheus-mcp-server/tests/test_config.py
  src/prometheus-mcp-server/tests/test_edge_cases.py
  src/prometheus-mcp-server/tests/test_error_handling.py
  src/prometheus-mcp-server/tests/test_init.py
  src/prometheus-mcp-server/tests/test_main.py
  src/prometheus-mcp-server/tests/test_make_prometheus_request.py
  src/prometheus-mcp-server/tests/test_models.py
  src/prometheus-mcp-server/tests/test_prometheus_connection.py
  src/prometheus-mcp-server/tests/test_remaining_coverage.py
  src/prometheus-mcp-server/tests/test_server.py
  src/prometheus-mcp-server/uv.lock
Labels: new mcp server

#574 fix: (eks-mcp-server) prevent server from crashing on launch with invalid AWS credentials
  src/eks-mcp-server/awslabs/eks_mcp_server/aws_helper.py
  src/eks-mcp-server/awslabs/eks_mcp_server/iam_handler.py
  src/eks-mcp-server/awslabs/eks_mcp_server/k8s_client_cache.py
  src/eks-mcp-server/tests/test_aws_helper.py
  src/eks-mcp-server/tests/test_eks_stack_handler.py
  src/eks-mcp-server/tests/test_iam_handler.py
  src/eks-mcp-server/tests/test_k8s_client_cache.py
Labels: ready-for-merge

#587 fix: cost-analysis-mcp-server: Fix AWS Price List API filter field capitalization
  src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/server.py
Labels: ready-for-merge, waiting-for-codeowners

#593 fix: minor fixes in elasticache mcp server
  src/elasticache-mcp-server/README.md
  src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/cw/get_metric_statistics.py
  src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/serverless/create.py
  src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/serverless/delete.py
  src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/serverless/modify.py
  src/elasticache-mcp-server/tests/tools/cw/test_get_metric_statistics.py
  src/elasticache-mcp-server/uv.lock
  src/memcached-mcp-server/uv.lock
  src/valkey-mcp-server/uv.lock
Labels: ready-for-merge

#573 fix: Use consistent Docker image name for AWS Documentation MCP Server
  src/aws-documentation-mcp-server/README.md
Labels: ready-for-merge

#615 docs: remove unnecessary indentation in aurora-dsql-mcp-server.md
  docs/servers/aurora-dsql-mcp-server.md
Labels: ready-for-merge

#621 feat: Add AWS IAM MCP Server
  .github/CODEOWNERS
  README.md
  docs/index.md
  docs/servers/iam-mcp-server.md
  mkdocs.yml
  src/iam-mcp-server/.gitignore
  src/iam-mcp-server/.python-version
  src/iam-mcp-server/CHANGELOG.md
  src/iam-mcp-server/DESIGN_COMPLIANCE.md
  src/iam-mcp-server/Dockerfile
  src/iam-mcp-server/LICENSE
  src/iam-mcp-server/NOTICE
  src/iam-mcp-server/README.md
  src/iam-mcp-server/awslabs/__init__.py
  src/iam-mcp-server/awslabs/iam_mcp_server/__init__.py
  src/iam-mcp-server/awslabs/iam_mcp_server/aws_client.py
  src/iam-mcp-server/awslabs/iam_mcp_server/context.py
  src/iam-mcp-server/awslabs/iam_mcp_server/errors.py
  src/iam-mcp-server/awslabs/iam_mcp_server/models.py
  src/iam-mcp-server/awslabs/iam_mcp_server/server.py
  src/iam-mcp-server/docker-healthcheck.sh
  src/iam-mcp-server/pyproject.toml
  src/iam-mcp-server/run_tests.sh
  src/iam-mcp-server/tests/test_context.py
  src/iam-mcp-server/tests/test_errors.py
  src/iam-mcp-server/tests/test_server.py
  src/iam-mcp-server/uv.lock
Labels: new mcp server

#543 refactor: remove unused param
  src/eks-mcp-server/awslabs/eks_mcp_server/iam_handler.py
Labels: ready-for-merge

#632 feat(aurora-dsql): enhance readonly mode enforcement
  src/aurora-dsql-mcp-server/README.md
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/consts.py
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/mutable_sql_detector.py
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/server.py
  src/aurora-dsql-mcp-server/tests/test_readonly_enforcement.py
  src/aurora-dsql-mcp-server/tests/test_server.py
Labels: ready-for-merge

#641 fix: remove pre-commit duplicate, use detect secrets
  .gitallowed
  src/openapi-mcp-server/.pre-commit-config.yaml
Labels: ready-for-merge

#669 feat: Amazon Redshift MCP Server
  .github/CODEOWNERS
  README.md
  docs/servers/redshift-mcp-server.md
  mkdocs.yml
  src/redshift-mcp-server/.gitignore
  src/redshift-mcp-server/.python-version
  src/redshift-mcp-server/CHANGELOG.md
  src/redshift-mcp-server/Dockerfile
  src/redshift-mcp-server/LICENSE
  src/redshift-mcp-server/NOTICE
  src/redshift-mcp-server/README.md
  src/redshift-mcp-server/awslabs/__init__.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/__init__.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/consts.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/models.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/redshift.py
  src/redshift-mcp-server/awslabs/redshift_mcp_server/server.py
  src/redshift-mcp-server/docker-healthcheck.sh
  src/redshift-mcp-server/pyproject.toml
  src/redshift-mcp-server/tests/test_init.py
  src/redshift-mcp-server/tests/test_main.py
  src/redshift-mcp-server/tests/test_redshift.py
  src/redshift-mcp-server/tests/test_server.py
  src/redshift-mcp-server/uv.lock
Labels: new mcp server

#679 refactor(resource-management): implement full CRUDL API with direct boto3 mapping and fix service events bugs
  src/ecs-mcp-server/README.md
  src/ecs-mcp-server/awslabs/ecs_mcp_server/api/resource_management.py
  src/ecs-mcp-server/awslabs/ecs_mcp_server/api/troubleshooting_tools/fetch_service_events.py
  src/ecs-mcp-server/awslabs/ecs_mcp_server/modules/resource_management.py
  src/ecs-mcp-server/tests/unit/api/test_resource_management_api.py
  src/ecs-mcp-server/tests/unit/modules/test_resource_management_module.py
  src/ecs-mcp-server/tests/unit/test_resource_management.py
  src/ecs-mcp-server/tests/unit/test_resource_management_api_operation.py
  src/ecs-mcp-server/tests/unit/test_resource_management_tool.py
  src/ecs-mcp-server/tests/unit/troubleshooting_tools/test_fetch_service_events.py
Labels: awaiting-user-feedback, waiting-for-codeowners
