Repository awslabs/mcp, pull requests merged in 2025-05, with the labels that each got.

#239 feat: claude code review
  .github/workflows/CLAUDE_PR_REVIEW_GUIDE.md
  .github/workflows/claude.yml
Labels: code-review

#227 refactor(cdk): dynamic genai cdk construct fetching
  src/cdk-mcp-server/awslabs/cdk_mcp_server/core/resources.py
  src/cdk-mcp-server/awslabs/cdk_mcp_server/core/server.py
  src/cdk-mcp-server/awslabs/cdk_mcp_server/core/tools.py
  src/cdk-mcp-server/awslabs/cdk_mcp_server/data/genai_cdk_loader.py
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/actiongroups.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/alias.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/collaboration.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/creation.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/custom_orchestration.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/overview.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/agent/prompt_override.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/bedrockguardrails.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/chunking.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/datasources.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/kendra.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/overview.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/parsing.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/transformation.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/vector/aurora.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/vector/creation.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/vector/opensearch.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/knowledgebases/vector/pinecone.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/bedrock/profiles.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/opensearch-vectorindex/overview.md
  src/cdk-mcp-server/awslabs/cdk_mcp_server/static/genai_cdk/opensearchserverless/overview.md
  src/cdk-mcp-server/tests/core/test_resources.py
  src/cdk-mcp-server/tests/core/test_resources_enhanced.py
  src/cdk-mcp-server/tests/core/test_search_utils.py
  src/cdk-mcp-server/tests/core/test_server.py
  src/cdk-mcp-server/tests/core/test_tools.py
  src/cdk-mcp-server/tests/data/test_cdk_nag_parser.py
  src/cdk-mcp-server/tests/data/test_genai_cdk_loader.py
  src/cdk-mcp-server/tests/data/test_lambda_powertools_loader.py
  src/cdk-mcp-server/tests/data/test_schema_generator.py
  src/cdk-mcp-server/tests/data/test_solutions_constructs_parser.py
  src/cdk-mcp-server/uv.lock
Labels: code-review

#245 docs: how to remediate detected secrets
  DEVELOPER_GUIDE.md
Labels: code-review

#180 feat(new MCP server): Add Git Repository Research MCP Server
  docs/servers/git-repo-research-mcp-server.md
  mkdocs.yml
  src/git-repo-research-mcp-server/.gitignore
  src/git-repo-research-mcp-server/.pre-commit-config.yaml
  src/git-repo-research-mcp-server/.python-version
  src/git-repo-research-mcp-server/CHANGELOG.md
  src/git-repo-research-mcp-server/LICENSE
  src/git-repo-research-mcp-server/NOTICE
  src/git-repo-research-mcp-server/README.md
  src/git-repo-research-mcp-server/awslabs/__init__.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/__init__.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/defaults.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/embeddings.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/github_search.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/indexer.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/models.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/repository.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/search.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/server.py
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/utils.py
  src/git-repo-research-mcp-server/pyproject.toml
  src/git-repo-research-mcp-server/run_tests.sh
  src/git-repo-research-mcp-server/tests/__init__.py
  src/git-repo-research-mcp-server/tests/conftest.py
  src/git-repo-research-mcp-server/tests/test_errors_repository.py
  src/git-repo-research-mcp-server/tests/test_github_search_edge_cases.py
  src/git-repo-research-mcp-server/tests/test_graphql_github_search.py
  src/git-repo-research-mcp-server/tests/test_local_repository.py
  src/git-repo-research-mcp-server/tests/test_repository_utils.py
  src/git-repo-research-mcp-server/tests/test_rest_github_search.py
  src/git-repo-research-mcp-server/tests/test_search.py
  src/git-repo-research-mcp-server/tests/test_server.py
  src/git-repo-research-mcp-server/tests/test_url_repository.py
  src/git-repo-research-mcp-server/uv.lock
Labels: hold-merging, new mcp server

#258 fear: almost zero change in code coverage
  .github/codecov.yml
Labels: code-review

#266 feat: bedrock kb retrieval rerank option
  .secrets.baseline
  samples/mcp-integration-with-kb/README.md
  src/bedrock-kb-retrieval-mcp-server/README.md
  src/bedrock-kb-retrieval-mcp-server/awslabs/bedrock_kb_retrieval_mcp_server/knowledgebases/retrieval.py
  src/bedrock-kb-retrieval-mcp-server/awslabs/bedrock_kb_retrieval_mcp_server/server.py
  src/bedrock-kb-retrieval-mcp-server/tests/test_env_config.py
  src/bedrock-kb-retrieval-mcp-server/tests/test_retrieval.py
  src/bedrock-kb-retrieval-mcp-server/uv.lock
Labels: code-review

#280 feat: default devcontainer
  .devcontainer/devcontainer.json
  .github/CODEOWNERS
Labels: code-review

#161 feat: Adding AWS Location MCP server
  .secrets.baseline
  README.md
  src/aws-location-mcp-server/.gitignore
  src/aws-location-mcp-server/.pre-commit-config.yaml
  src/aws-location-mcp-server/.python-version
  src/aws-location-mcp-server/CHANGELOG.md
  src/aws-location-mcp-server/Dockerfile
  src/aws-location-mcp-server/LICENSE
  src/aws-location-mcp-server/NOTICE
  src/aws-location-mcp-server/README.md
  src/aws-location-mcp-server/awslabs/__init__.py
  src/aws-location-mcp-server/awslabs/aws_location_server/__init__.py
  src/aws-location-mcp-server/awslabs/aws_location_server/server.py
  src/aws-location-mcp-server/docker-healthcheck.sh
  src/aws-location-mcp-server/pyproject.toml
  src/aws-location-mcp-server/tests/__init__.py
  src/aws-location-mcp-server/tests/conftest.py
  src/aws-location-mcp-server/tests/run_integration_tests.sh
  src/aws-location-mcp-server/tests/test_server.py
  src/aws-location-mcp-server/tests/test_server_integration.py
  src/aws-location-mcp-server/uv.lock
Labels: new mcp server

#295 fix: nav terraform mcp server md typo
  mkdocs.yml
Labels: code-review

#292 feat: push container images
  .github/actions/build-and-push-container-image/action.yml
  .github/workflows/code-review-process.yml
  .github/workflows/code-review-request.yml
  .github/workflows/release.yml
Labels: code-review

#301 fix: correct path to public ecr
  .github/actions/build-and-push-container-image/action.yml
  .github/codecov.yml
  src/core-mcp-server/awslabs/core_mcp_server/__init__.py
Labels: bug, code-review, docker

#302 fix: default dev container
  .devcontainer/devcontainer.json
Labels: code-review

#277 feat(cost-analysis-mcp-server): terraform module analyzer
  src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/terraform_analyzer.py
  src/cost-analysis-mcp-server/tests/test_terraform_analyzer.py
  src/cost-analysis-mcp-server/uv.lock
Labels: code-review

#313 fix: cyclonedx to JSON format
  .github/workflows/python.yml
Labels: code-review

#321 fix: pull_request_target is the event type
  .github/workflows/claude.yml
Labels: code-review

#319 fix(diagram-mcp): filter icons/ reduce input tokens
  src/aws-diagram-mcp-server/awslabs/aws_diagram_mcp_server/diagrams_tools.py
  src/aws-diagram-mcp-server/awslabs/aws_diagram_mcp_server/models.py
  src/aws-diagram-mcp-server/awslabs/aws_diagram_mcp_server/server.py
  src/aws-diagram-mcp-server/tests/test_diagrams.py
  src/aws-diagram-mcp-server/tests/test_server.py
  src/aws-diagram-mcp-server/uv.lock
Labels: code-review

#326 fix: release multiple digests
  .github/actions/build-and-push-container-image/action.yml
  src/lambda-mcp-server/awslabs/lambda_mcp_server/__init__.py
  src/postgres-mcp-server/awslabs/postgres_mcp_server/__init__.py
Labels: code-review

#296 feat(new MCP server): add Code Documentation Generation MCP Server
  README.md
  docs/index.md
  docs/servers/code-doc-gen-mcp-server.md
  src/code-doc-gen-mcp-server/.gitignore
  src/code-doc-gen-mcp-server/.pre-commit-config.yaml
  src/code-doc-gen-mcp-server/.python-version
  src/code-doc-gen-mcp-server/CHANGELOG.md
  src/code-doc-gen-mcp-server/LICENSE
  src/code-doc-gen-mcp-server/NOTICE
  src/code-doc-gen-mcp-server/README.md
  src/code-doc-gen-mcp-server/awslabs/__init__.py
  src/code-doc-gen-mcp-server/awslabs/code_doc_gen_mcp_server/__init__.py
  src/code-doc-gen-mcp-server/awslabs/code_doc_gen_mcp_server/server.py
  src/code-doc-gen-mcp-server/awslabs/code_doc_gen_mcp_server/utils/doc_generator.py
  src/code-doc-gen-mcp-server/awslabs/code_doc_gen_mcp_server/utils/models.py
  src/code-doc-gen-mcp-server/awslabs/code_doc_gen_mcp_server/utils/repomix_manager.py
  src/code-doc-gen-mcp-server/awslabs/code_doc_gen_mcp_server/utils/templates.py
  src/code-doc-gen-mcp-server/pyproject.toml
  src/code-doc-gen-mcp-server/tests/test_doc_generator.py
  src/code-doc-gen-mcp-server/tests/test_doc_generator_edge_cases.py
  src/code-doc-gen-mcp-server/tests/test_init.py
  src/code-doc-gen-mcp-server/tests/test_main.py
  src/code-doc-gen-mcp-server/tests/test_repomix_manager.py
  src/code-doc-gen-mcp-server/tests/test_repomix_manager_scenarios.py
  src/code-doc-gen-mcp-server/tests/test_repomix_statistics.py
  src/code-doc-gen-mcp-server/tests/test_server.py
  src/code-doc-gen-mcp-server/tests/test_server_extended.py
  src/code-doc-gen-mcp-server/tests/test_templates.py
  src/code-doc-gen-mcp-server/uv.lock
Labels: code-review, new mcp server

#287 feat: Add Amazon SNS / SQS MCP Server
  src/amazon-sns-sqs-mcp-server/.gitignore
  src/amazon-sns-sqs-mcp-server/.pre-commit-config.yaml
  src/amazon-sns-sqs-mcp-server/.python-version
  src/amazon-sns-sqs-mcp-server/CHANGELOG.md
  src/amazon-sns-sqs-mcp-server/Dockerfile
  src/amazon-sns-sqs-mcp-server/LICENSE
  src/amazon-sns-sqs-mcp-server/NOTICE
  src/amazon-sns-sqs-mcp-server/README.md
  src/amazon-sns-sqs-mcp-server/awslabs/__init__.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/__init__.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/common.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/consts.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/generator.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/server.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/sns.py
  src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/sqs.py
  src/amazon-sns-sqs-mcp-server/docker-healthcheck.sh
  src/amazon-sns-sqs-mcp-server/print_tools.py
  src/amazon-sns-sqs-mcp-server/pyproject.toml
  src/amazon-sns-sqs-mcp-server/run_tests.sh
  src/amazon-sns-sqs-mcp-server/tests/.gitignore
  src/amazon-sns-sqs-mcp-server/tests/README.md
  src/amazon-sns-sqs-mcp-server/tests/__init__.py
  src/amazon-sns-sqs-mcp-server/tests/test_common.py
  src/amazon-sns-sqs-mcp-server/tests/test_generator.py
  src/amazon-sns-sqs-mcp-server/tests/test_server.py
  src/amazon-sns-sqs-mcp-server/tests/test_sns.py
  src/amazon-sns-sqs-mcp-server/tests/test_sqs.py
  src/amazon-sns-sqs-mcp-server/uv.lock
Labels: code-review, new mcp server

#271 feat: Add Amazon MQ MCP Server
  src/amazon-mq-mcp-server/.gitignore
  src/amazon-mq-mcp-server/.pre-commit-config.yaml
  src/amazon-mq-mcp-server/.python-version
  src/amazon-mq-mcp-server/CHANGELOG.md
  src/amazon-mq-mcp-server/Dockerfile
  src/amazon-mq-mcp-server/LICENSE
  src/amazon-mq-mcp-server/NOTICE
  src/amazon-mq-mcp-server/README.md
  src/amazon-mq-mcp-server/awslabs/__init__.py
  src/amazon-mq-mcp-server/awslabs/amazon_mq_mcp_server/__init__.py
  src/amazon-mq-mcp-server/awslabs/amazon_mq_mcp_server/aws_service_mcp_generator.py
  src/amazon-mq-mcp-server/awslabs/amazon_mq_mcp_server/consts.py
  src/amazon-mq-mcp-server/awslabs/amazon_mq_mcp_server/server.py
  src/amazon-mq-mcp-server/docker-healthcheck.sh
  src/amazon-mq-mcp-server/pyproject.toml
  src/amazon-mq-mcp-server/tests/.gitignore
  src/amazon-mq-mcp-server/tests/__init__.py
  src/amazon-mq-mcp-server/tests/test_aws_service_mcp_generator.py
  src/amazon-mq-mcp-server/tests/test_server.py
  src/amazon-mq-mcp-server/uv.lock
Labels: code-review, new mcp server

#325 feat: update CODEOWNERS for each source
  .github/CODEOWNERS
Labels: code-review

#335 fix: replace mermaid diagram with image for security compliance
  mkdocs.yml
Labels: code-review

#336 fix: mermaid2 plugin version and CDN location
  .github/workflows/gh-pages.yml
  mkdocs.yml
Labels: code-review

#307 feat(new MCP server): Add CloudFormation MCP Server
  README.md
  docs/index.md
  docs/servers/cfn-mcp-server.md
  mkdocs.yml
  src/cfn-mcp-server/.gitignore
  src/cfn-mcp-server/.pre-commit-config.yaml
  src/cfn-mcp-server/.python-version
  src/cfn-mcp-server/CHANGELOG.md
  src/cfn-mcp-server/Dockerfile
  src/cfn-mcp-server/LICENSE
  src/cfn-mcp-server/NOTICE
  src/cfn-mcp-server/README.md
  src/cfn-mcp-server/awslabs/__init__.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/__init__.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/aws_client.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/cloud_control_utils.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/context.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/errors.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/schema_manager.py
  src/cfn-mcp-server/awslabs/cfn_mcp_server/server.py
  src/cfn-mcp-server/docker-healthcheck.sh
  src/cfn-mcp-server/pyproject.toml
  src/cfn-mcp-server/run_tests.sh
  src/cfn-mcp-server/tests/__init__.py
  src/cfn-mcp-server/tests/test_aws_client.py
  src/cfn-mcp-server/tests/test_cloud_control_utils.py
  src/cfn-mcp-server/tests/test_errors.py
  src/cfn-mcp-server/tests/test_init.py
  src/cfn-mcp-server/tests/test_main.py
  src/cfn-mcp-server/tests/test_schema_manager.py
  src/cfn-mcp-server/tests/test_server.py
  src/cfn-mcp-server/uv.lock
Labels: code-review, new mcp server

#259 fix: removed union for parameters for cursor compatibility (aws-documentation)
  src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/server.py
Labels: code-review

#323 feat: DynamoDB Local MCP Server #316
  README.md
  docs/index.md
  docs/servers/dynamodb-mcp-server.md
  src/dynamodb-mcp-server/.gitignore
  src/dynamodb-mcp-server/.pre-commit-config.yaml
  src/dynamodb-mcp-server/.python-version
  src/dynamodb-mcp-server/CHANGELOG.md
  src/dynamodb-mcp-server/Dockerfile
  src/dynamodb-mcp-server/LICENSE
  src/dynamodb-mcp-server/NOTICE
  src/dynamodb-mcp-server/README.md
  src/dynamodb-mcp-server/awslabs/__init__.py
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/__init__.py
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/common.py
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/dynamodb_server.py
  src/dynamodb-mcp-server/docker-healthcheck.sh
  src/dynamodb-mcp-server/pyproject.toml
  src/dynamodb-mcp-server/tests/test_dynamodb_server.py
  src/dynamodb-mcp-server/uv.lock
Labels: code-review, new mcp server

#344 fix: docker healthchecks
  src/amazon-mq-mcp-server/docker-healthcheck.sh
  src/amazon-sns-sqs-mcp-server/docker-healthcheck.sh
  src/aws-diagram-mcp-server/docker-healthcheck.sh
  src/aws-documentation-mcp-server/docker-healthcheck.sh
  src/aws-location-mcp-server/docker-healthcheck.sh
  src/bedrock-kb-retrieval-mcp-server/docker-healthcheck.sh
  src/cdk-mcp-server/docker-healthcheck.sh
  src/cfn-mcp-server/docker-healthcheck.sh
  src/core-mcp-server/docker-healthcheck.sh
  src/cost-analysis-mcp-server/docker-healthcheck.sh
  src/dynamodb-mcp-server/docker-healthcheck.sh
  src/lambda-mcp-server/docker-healthcheck.sh
  src/nova-canvas-mcp-server/docker-healthcheck.sh
  src/postgres-mcp-server/docker-healthcheck.sh
  src/terraform-mcp-server/docker-healthcheck.sh
Labels: code-review

#347 fix: a typo in README + rename dynamodb_server to server
  src/dynamodb-mcp-server/README.md
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/server.py
  src/dynamodb-mcp-server/tests/test_dynamodb_server.py
  src/dynamodb-mcp-server/uv.lock
Labels: code-review

#314 fix: permissions at the top-level of workflows
  .github/workflows/bandit.yml
  .github/workflows/cfn_nag.yml
  .github/workflows/checkov.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review-action.yml
  .github/workflows/gh-pages.yml
  .github/workflows/powershell.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/python.yml
  .github/workflows/release.yml
  .github/workflows/scanners.yml
  .github/workflows/scorecard-analysis.yml
  .github/workflows/semgrep.yml
  .github/workflows/stale.yml
  .github/workflows/trivy.yml
Labels: code-review

#327 chore: Temporary Credentials Support, correct the branding to "Amazon Location Service"
  .secrets.baseline
  src/aws-location-mcp-server/README.md
  src/aws-location-mcp-server/awslabs/aws_location_server/server.py
  src/aws-location-mcp-server/tests/test_server.py
Labels: code-review

#349 fix(synthetic_server): Ensures compliance with regex pattern error
  src/syntheticdata-mcp-server/README.md
  src/syntheticdata-mcp-server/awslabs/syntheticdata_mcp_server/server.py
  src/syntheticdata-mcp-server/tests/test_server.py
  src/syntheticdata-mcp-server/uv.lock
Labels: code-review

#300 feat(server): Amazon ElastiCache Memcached MCP Server
  README.md
  docs/index.md
  docs/servers/memcached-mcp-server.md
  src/memcached-mcp-server/.gitignore
  src/memcached-mcp-server/.pre-commit-config.yaml
  src/memcached-mcp-server/.python-version
  src/memcached-mcp-server/CHANGELOG.md
  src/memcached-mcp-server/Dockerfile
  src/memcached-mcp-server/LICENSE
  src/memcached-mcp-server/NOTICE
  src/memcached-mcp-server/README.md
  src/memcached-mcp-server/awslabs/__init__.py
  src/memcached-mcp-server/awslabs/memcached_mcp_server/__init__.py
  src/memcached-mcp-server/awslabs/memcached_mcp_server/common/config.py
  src/memcached-mcp-server/awslabs/memcached_mcp_server/common/connection.py
  src/memcached-mcp-server/awslabs/memcached_mcp_server/common/server.py
  src/memcached-mcp-server/awslabs/memcached_mcp_server/main.py
  src/memcached-mcp-server/awslabs/memcached_mcp_server/tools/cache.py
  src/memcached-mcp-server/docker-healthcheck.sh
  src/memcached-mcp-server/pyproject.toml
  src/memcached-mcp-server/tests/test_cache.py
  src/memcached-mcp-server/tests/test_connection.py
  src/memcached-mcp-server/tests/test_init.py
  src/memcached-mcp-server/tests/test_main.py
  src/memcached-mcp-server/uv.lock
Labels: code-review, new mcp server

#291 feat(server): Amazon ElastiCache/MemoryDB Valkey MCP Server
  README.md
  docs/index.md
  docs/servers/valkey-mcp-server.md
  src/valkey-mcp-server/.gitignore
  src/valkey-mcp-server/.pre-commit-config.yaml
  src/valkey-mcp-server/.python-version
  src/valkey-mcp-server/CHANGELOG.md
  src/valkey-mcp-server/Dockerfile
  src/valkey-mcp-server/LICENSE
  src/valkey-mcp-server/NOTICE
  src/valkey-mcp-server/README.md
  src/valkey-mcp-server/awslabs/__init__.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/__init__.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/common/__init__.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/common/config.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/common/connection.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/common/server.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/main.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/__init__.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/bitmap.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/hash.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/hyperloglog.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/json.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/list.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/misc.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/server_management.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/set.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/sorted_set.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/stream.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/tools/string.py
  src/valkey-mcp-server/awslabs/valkey_mcp_server/version.py
  src/valkey-mcp-server/docker-healthcheck.sh
  src/valkey-mcp-server/pyproject.toml
  src/valkey-mcp-server/tests/test_bitmap.py
  src/valkey-mcp-server/tests/test_config.py
  src/valkey-mcp-server/tests/test_connection.py
  src/valkey-mcp-server/tests/test_hash.py
  src/valkey-mcp-server/tests/test_hyperloglog.py
  src/valkey-mcp-server/tests/test_init.py
  src/valkey-mcp-server/tests/test_json.py
  src/valkey-mcp-server/tests/test_list.py
  src/valkey-mcp-server/tests/test_main.py
  src/valkey-mcp-server/tests/test_server_management.py
  src/valkey-mcp-server/tests/test_set.py
  src/valkey-mcp-server/tests/test_sorted_set.py
  src/valkey-mcp-server/tests/test_sorted_set_additional.py
  src/valkey-mcp-server/tests/test_stream.py
  src/valkey-mcp-server/tests/test_string.py
  src/valkey-mcp-server/uv.lock
Labels: code-review, new mcp server

#357 fix: allow a code review when labeled hold-merging
  .github/workflows/claude.yml
Labels: github_actions, code-review

#358 fix: correct fastmcp
  src/amazon-sns-sqs-mcp-server/pyproject.toml
  src/amazon-sns-sqs-mcp-server/uv.lock
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/server.py
  src/dynamodb-mcp-server/pyproject.toml
  src/dynamodb-mcp-server/uv.lock
Labels: code-review

#360 docs: Update ElastiCache Valkey and Memcached readme
  README.md
  src/memcached-mcp-server/ELASTICACHECONNECT.md
  src/memcached-mcp-server/README.md
  src/valkey-mcp-server/ELASTICACHECONNECT.md
  src/valkey-mcp-server/README.md
Labels: code-review

#352 fix: codeownership with admins
  .github/CODEOWNERS
Labels: code-review

#363 fix(doc): syntax errors in mcp.json example
  README.md
Labels: code-review

#371 fix: increase claude code timeout
  .github/workflows/claude.yml
Labels: code-review

#376 fix(Postgres): fix issue and beef up overall security test cases
  src/postgres-mcp-server/awslabs/postgres_mcp_server/mutable_sql_detector.py
  src/postgres-mcp-server/awslabs/postgres_mcp_server/server.py
  src/postgres-mcp-server/tests/conftest.py
  src/postgres-mcp-server/tests/test_server.py
Labels: code-review

#328 feat: Aurora DSQL MCP Server
  README.md
  docs/index.md
  docs/servers/aurora-dsql-mcp-server.md
  src/aurora-dsql-mcp-server/.gitignore
  src/aurora-dsql-mcp-server/.pre-commit-config.yaml
  src/aurora-dsql-mcp-server/.python-version
  src/aurora-dsql-mcp-server/CHANGELOG.md
  src/aurora-dsql-mcp-server/Dockerfile
  src/aurora-dsql-mcp-server/LICENSE
  src/aurora-dsql-mcp-server/NOTICE
  src/aurora-dsql-mcp-server/README.md
  src/aurora-dsql-mcp-server/awslabs/__init__.py
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/__init__.py
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/consts.py
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/server.py
  src/aurora-dsql-mcp-server/docker-healthcheck.sh
  src/aurora-dsql-mcp-server/pyproject.toml
  src/aurora-dsql-mcp-server/tests/test_init.py
  src/aurora-dsql-mcp-server/tests/test_main.py
  src/aurora-dsql-mcp-server/tests/test_server.py
  src/aurora-dsql-mcp-server/uv.lock
Labels: code-review, new mcp server

#362 feat(documentdb): add DocumentDB MCP server
  docs/index.md
  docs/servers/documentdb-mcp-server.md
  src/documentdb-mcp-server/.gitignore
  src/documentdb-mcp-server/.pre-commit-config.yaml
  src/documentdb-mcp-server/.python-version
  src/documentdb-mcp-server/CHANGELOG.md
  src/documentdb-mcp-server/LICENSE
  src/documentdb-mcp-server/NOTICE
  src/documentdb-mcp-server/README.md
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/__init__.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/analytic_tools.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/config.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/connection_tools.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/db_management_tools.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/query_tools.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/server.py
  src/documentdb-mcp-server/awslabs/documentdb_mcp_server/write_tools.py
  src/documentdb-mcp-server/pyproject.toml
  src/documentdb-mcp-server/tests/conftest.py
  src/documentdb-mcp-server/tests/test_analytic_tools.py
  src/documentdb-mcp-server/tests/test_connection_tools.py
  src/documentdb-mcp-server/tests/test_db_management_tools.py
  src/documentdb-mcp-server/tests/test_init.py
  src/documentdb-mcp-server/tests/test_main.py
  src/documentdb-mcp-server/tests/test_query_tools.py
  src/documentdb-mcp-server/tests/test_write_tools.py
  src/documentdb-mcp-server/uv.lock
Labels: code-review, new mcp server

#241 feat(new MCP server): Add Frontend MCP Server
  README.md
  docs/index.md
  docs/servers/frontend-mcp-server.md
  src/frontend-mcp-server/.gitignore
  src/frontend-mcp-server/.pre-commit-config.yaml
  src/frontend-mcp-server/.python-version
  src/frontend-mcp-server/CHANGELOG.md
  src/frontend-mcp-server/LICENSE
  src/frontend-mcp-server/NOTICE
  src/frontend-mcp-server/README.md
  src/frontend-mcp-server/awslabs/__init__.py
  src/frontend-mcp-server/awslabs/frontend_mcp_server/__init__.py
  src/frontend-mcp-server/awslabs/frontend_mcp_server/server.py
  src/frontend-mcp-server/awslabs/frontend_mcp_server/static/react/essential-knowledge.md
  src/frontend-mcp-server/awslabs/frontend_mcp_server/static/react/troubleshooting.md
  src/frontend-mcp-server/awslabs/frontend_mcp_server/utils/__init__.py
  src/frontend-mcp-server/awslabs/frontend_mcp_server/utils/file_utils.py
  src/frontend-mcp-server/pyproject.toml
  src/frontend-mcp-server/tests/test_file_utils.py
  src/frontend-mcp-server/tests/test_init.py
  src/frontend-mcp-server/tests/test_main.py
  src/frontend-mcp-server/tests/test_server.py
  src/frontend-mcp-server/uv.lock
Labels: code-review, new mcp server

#387 fix(KendraIndex): missing dependency in pyproject.toml
  src/amazon-kendra-index-mcp-server/awslabs/amazon_kendra_index_mcp_server/server.py
  src/amazon-kendra-index-mcp-server/pyproject.toml
  src/amazon-kendra-index-mcp-server/uv.lock
Labels: code-review

#394 fix(lambda-handler): Fix the status code for notifications
  src/mcp-lambda-handler/awslabs/mcp_lambda_handler/mcp_lambda_handler.py
  src/mcp-lambda-handler/tests/test_lambda_handler.py
Labels: code-review

#391 chore(doc): update readme
  README.md
  docs/index.md
  docs/servers/amazon-neptune-mcp-server.md
Labels: code-review

#407 chore(doc): improve service naming consistency and fix links
  README.md
  docs/index.md
  src/memcached-mcp-server/ELASTICACHECONNECT.md
  src/valkey-mcp-server/ELASTICACHECONNECT.md
Labels: code-review

#400 perf: Dsql connection reuse
  src/aurora-dsql-mcp-server/README.md
  src/aurora-dsql-mcp-server/awslabs/aurora_dsql_mcp_server/server.py
  src/aurora-dsql-mcp-server/tests/test_connection_reuse.py
  src/aurora-dsql-mcp-server/tests/test_profile_option.py
  src/aurora-dsql-mcp-server/tests/test_server.py
  src/aurora-dsql-mcp-server/uv.lock
Labels: code-review

#414 fix: support read-only mode for dynamodb mcp
  src/dynamodb-mcp-server/README.md
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/common.py
  src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/server.py
  src/dynamodb-mcp-server/tests/test_dynamodb_server.py
  src/dynamodb-mcp-server/tests/test_readonly_delete_table.py
Labels: code-review

#412 fix(doc): JSON syntax errors in mcp.json example
  README.md
Labels: code-review

#410 fix(samples): Update MultiServerMCPClient usage for langchain-mcp-adapters 0.1.0
  samples/mcp-integration-with-kb/clients/client_server.py
  samples/mcp-integration-with-nova-canvas/clients/client_server.py
Labels: code-review

#397 fix(tools): rename search_research_repository_suggestions to search_repositories_on_github
  README.md
  src/git-repo-research-mcp-server/README.md
  src/git-repo-research-mcp-server/awslabs/git_repo_research_mcp_server/server.py
  src/git-repo-research-mcp-server/tests/test_rest_github_search.py
  src/git-repo-research-mcp-server/uv.lock
Labels: code-review

#406 docs: Cleanup Sample + Remove Duplicate link into Documentation section
  README.md
Labels: code-review

#429 feat: Amazon EKS MCP Server
  .github/CODEOWNERS
  README.md
  docs/index.md
  docs/servers/eks-mcp-server.md
  src/eks-mcp-server/.gitignore
  src/eks-mcp-server/.pre-commit-config.yaml
  src/eks-mcp-server/.python-version
  src/eks-mcp-server/CHANGELOG.md
  src/eks-mcp-server/Dockerfile
  src/eks-mcp-server/LICENSE
  src/eks-mcp-server/NOTICE
  src/eks-mcp-server/README.md
  src/eks-mcp-server/awslabs/__init__.py
  src/eks-mcp-server/awslabs/eks_mcp_server/__init__.py
  src/eks-mcp-server/awslabs/eks_mcp_server/aws_helper.py
  src/eks-mcp-server/awslabs/eks_mcp_server/cloudwatch_handler.py
  src/eks-mcp-server/awslabs/eks_mcp_server/consts.py
  src/eks-mcp-server/awslabs/eks_mcp_server/eks_kb_handler.py
  src/eks-mcp-server/awslabs/eks_mcp_server/eks_stack_handler.py
  src/eks-mcp-server/awslabs/eks_mcp_server/iam_handler.py
  src/eks-mcp-server/awslabs/eks_mcp_server/k8s_apis.py
  src/eks-mcp-server/awslabs/eks_mcp_server/k8s_client_cache.py
  src/eks-mcp-server/awslabs/eks_mcp_server/k8s_handler.py
  src/eks-mcp-server/awslabs/eks_mcp_server/logging_helper.py
  src/eks-mcp-server/awslabs/eks_mcp_server/models.py
  src/eks-mcp-server/awslabs/eks_mcp_server/server.py
  src/eks-mcp-server/awslabs/eks_mcp_server/templates/eks-templates/eks-with-vpc.yaml
  src/eks-mcp-server/awslabs/eks_mcp_server/templates/k8s-templates/deployment.yaml
  src/eks-mcp-server/awslabs/eks_mcp_server/templates/k8s-templates/service.yaml
  src/eks-mcp-server/docker-healthcheck.sh
  src/eks-mcp-server/pyproject.toml
  src/eks-mcp-server/tests/test_aws_helper.py
  src/eks-mcp-server/tests/test_cloudwatch_handler.py
  src/eks-mcp-server/tests/test_eks_kb_handler.py
  src/eks-mcp-server/tests/test_eks_stack_handler.py
  src/eks-mcp-server/tests/test_iam_handler.py
  src/eks-mcp-server/tests/test_init.py
  src/eks-mcp-server/tests/test_k8s_apis.py
  src/eks-mcp-server/tests/test_k8s_client_cache.py
  src/eks-mcp-server/tests/test_k8s_handler.py
  src/eks-mcp-server/tests/test_logging_helper.py
  src/eks-mcp-server/tests/test_main.py
  src/eks-mcp-server/tests/test_models.py
  src/eks-mcp-server/tests/test_server.py
  src/eks-mcp-server/uv.lock
Labels: code-review, new mcp server

#379 feat(server): AWS Support API MCP Server (#350) #379
  docs/servers/aws-support-mcp-server.md
  mkdocs.yml
  src/aws-support-mcp-server/.python-version
  src/aws-support-mcp-server/README.md
  src/aws-support-mcp-server/awslabs/__init__.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/__init__.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/client.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/consts.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/debug_helper.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/errors.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/formatters.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/models.py
  src/aws-support-mcp-server/awslabs/aws_support_mcp_server/server.py
  src/aws-support-mcp-server/pyproject.toml
  src/aws-support-mcp-server/tests/__init__.py
  src/aws-support-mcp-server/tests/conftests.py
  src/aws-support-mcp-server/tests/test_aws_support_mcp_server.py
  src/aws-support-mcp-server/tests/test_models.py
  src/aws-support-mcp-server/uv.lock
Labels: new mcp server

#436 feat(logs): Implement cloudwatch logs MCP server
  .github/CODEOWNERS
  README.md
  docs/index.md
  docs/servers/cloudwatch-logs-mcp-server.md
  src/cloudwatch-logs-mcp-server/.gitignore
  src/cloudwatch-logs-mcp-server/.pre-commit-config.yaml
  src/cloudwatch-logs-mcp-server/.python-version
  src/cloudwatch-logs-mcp-server/CHANGELOG.md
  src/cloudwatch-logs-mcp-server/Dockerfile
  src/cloudwatch-logs-mcp-server/LICENSE
  src/cloudwatch-logs-mcp-server/NOTICE
  src/cloudwatch-logs-mcp-server/README.md
  src/cloudwatch-logs-mcp-server/awslabs/__init__.py
  src/cloudwatch-logs-mcp-server/awslabs/cloudwatch_logs_mcp_server/__init__.py
  src/cloudwatch-logs-mcp-server/awslabs/cloudwatch_logs_mcp_server/common.py
  src/cloudwatch-logs-mcp-server/awslabs/cloudwatch_logs_mcp_server/models.py
  src/cloudwatch-logs-mcp-server/awslabs/cloudwatch_logs_mcp_server/server.py
  src/cloudwatch-logs-mcp-server/docker-healthcheck.sh
  src/cloudwatch-logs-mcp-server/pyproject.toml
  src/cloudwatch-logs-mcp-server/tests/test_init.py
  src/cloudwatch-logs-mcp-server/tests/test_main.py
  src/cloudwatch-logs-mcp-server/tests/test_models.py
  src/cloudwatch-logs-mcp-server/tests/test_server.py
  src/cloudwatch-logs-mcp-server/uv.lock
Labels: new mcp server

#464 fix(ecs-mcp-server): fix circular dependency in ecs infrastructure template
  src/ecs-mcp-server/awslabs/ecs_mcp_server/templates/ecs_infrastructure.json
Labels: bug, code-review

#466 chore: refactor serverless server and add user agents for sam cli and boto3 calls
  src/aws-serverless-mcp-server/README.md
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/models.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/resources/__init__.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/server.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/template/registry.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/guidance/__init__.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/guidance/deploy_serverless_app_help.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/guidance/get_iac_guidance.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/guidance/get_lambda_event_schemas.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/guidance/get_lambda_guidance.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/guidance/get_serverless_templates.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/__init__.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/sam_build.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/sam_deploy.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/sam_init.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/sam_local_invoke.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/sam_logs.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/schemas/__init__.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/schemas/describe_schema.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/schemas/list_registries.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/schemas/search_schema.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/webapps/__init__.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/webapps/configure_domain.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/webapps/deploy_webapp.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/webapps/get_metrics.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/webapps/update_webapp_frontend.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/webapps/webapp_deployment_help.py
  src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/utils/aws_client_helper.py
  src/aws-serverless-mcp-server/tests/test_cloudformation.py
  src/aws-serverless-mcp-server/tests/test_configure_domain.py
  src/aws-serverless-mcp-server/tests/test_deploy_serverless_app_help.py
  src/aws-serverless-mcp-server/tests/test_deploy_service.py
  src/aws-serverless-mcp-server/tests/test_deploy_webapp.py
  src/aws-serverless-mcp-server/tests/test_deployment_help.py
  src/aws-serverless-mcp-server/tests/test_frontend_uploader.py
  src/aws-serverless-mcp-server/tests/test_get_iac_guidance.py
  src/aws-serverless-mcp-server/tests/test_get_lambda_event_schemas.py
  src/aws-serverless-mcp-server/tests/test_get_lambda_guidance.py
  src/aws-serverless-mcp-server/tests/test_get_metrics.py
  src/aws-serverless-mcp-server/tests/test_get_serverless_templates.py
  src/aws-serverless-mcp-server/tests/test_models.py
  src/aws-serverless-mcp-server/tests/test_sam_build.py
  src/aws-serverless-mcp-server/tests/test_sam_deploy.py
  src/aws-serverless-mcp-server/tests/test_sam_init.py
  src/aws-serverless-mcp-server/tests/test_sam_local_invoke.py
  src/aws-serverless-mcp-server/tests/test_sam_logs.py
  src/aws-serverless-mcp-server/tests/test_schemas.py
  src/aws-serverless-mcp-server/tests/test_server.py
  src/aws-serverless-mcp-server/tests/test_update_webapp_frontend.py
  src/aws-serverless-mcp-server/uv.lock
Labels: code-review
